sudo: false

language: node_js
node_js:
  - '12'

cache: yarn

install:
  - yarn --frozen-lockfile --non-interactive --no-progress

script:
  # lint
  - yarn prettier:check
  # build
  - yarn build
  # tests
  - yarn test
  - yarn readme:check

deploy:
  - provider: script
    skip_cleanup: true
    script: yarn semantic-release
    on:
      branch: master
