// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var $$String = require("bs-platform/lib/js/string.js");

function toChar(symbol) {
  switch (symbol) {
    case /* Zero */0 :
        return /* "0" */48;
    case /* One */1 :
        return /* "1" */49;
    case /* Blank */2 :
        return /* " " */32;
    
  }
}

function toString(symbol) {
  return $$String.make(1, toChar(symbol));
}

function verbPhrase(symbol) {
  switch (symbol) {
    case /* Zero */0 :
        return "write a 0";
    case /* One */1 :
        return "write a 1";
    case /* Blank */2 :
        return "erase the head";
    
  }
}

exports.toChar = toChar;
exports.toString = toString;
exports.verbPhrase = verbPhrase;
/* No side effect */
